---
- name: Copying service-template to server
  become: true
  ansible.builtin.template:
    src: '{{ app_service_file }}'
    dest: /etc/systemd/system/{{ app_name }}.service
    mode: preserve

- name: Start service {{ app_name }}
  become: true
  ansible.builtin.systemd:
    name: '{{ app_name }}.service'
    state: reloaded
    daemon_reload: true
    enabled: '{{ app_autostart }}'
